name: CI/CD Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # - name: Run tests
      #   run: poetry run pytest

      - name: Lint code
        run: poetry run flake8 s3sync
