# name: Release Workflow

# on:
#   workflow_run:
#     workflows:
#       - "Pull Request CI"
#     types:
#       - completed

# jobs:
#   release:
#     name: Build, Package, and Release
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install poetry
#           poetry install

#       - name: Package wheel
#         run: poetry build

#       - name: Create GitHub Release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           files: dist/*.whl
